### ISSUE TITLE
You are trying to access item that no longer exists.

### ISSUE THREAD

**Issue by TheoGit** [Sitefinity-SDK/Telerik.Sitefinity.Samples.Locations#4]
Me again, it's been a while since I looked at this project and now have a much better understanding of the code - it's the "CreateBackendSections" and other Config functionality I'm interested in learning and applying to my own project.

When trying to run the app I get this error:
"You are trying to access item that no longer exists. The most probable reason is that it has been deleted by another user."

happening at this code: var pageFacade = fluent.Page()
SampleUtilities.cs line1561

**Comment by grumpycatsaysno** [comment]
Hello,

Thank you for your interest in the Locations sample. I tried to reproduce the error but to no avail. Could you please try to delete all configurations and the database and try to rerun the sample. I you receive the same error, please send me the error log and I'll investigate what could cause it.
